version: '3'

services:
  redis-server: 
    container_name: redis-server
    mem_limit: 1024m
    cpus: 1
    image: 'redis'
    ports:
      - "6379:6379"
    networks: 
      - audit-net
  audit-server:
    container_name: audit-server
    mem_limit: 1024m
    cpus: 1
    environment:
      - SERVER_PORT=8080
      - STORAGE_TYPE=kafka
      - REDIS_URL=redis-server:6379
      - REDIS_PASSWORD=
      - REDIS_KEY=audit_logs
      - KAFKA_URL=kafka-broker:29092
      - KAFKA_TOPIC=audit_logs
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - redis-server
    networks: 
      - audit-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    mem_limit: 1024m
    cpus: 1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: 
      - audit-net
  kafka-broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-broker
    mem_limit: 1024m
    cpus: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks: 
      - audit-net
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka-broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
networks:
  audit-net: