apiVersion: v1
kind: Service
metadata:
  labels:
    app: audit-server
  name: audit-server
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: audit-server
  type: ClusterIP